name: compile_hdc

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CLASSIC_TOKEN }}
          submodules: recursive
      # - uses: bettermarks/action-artifact-download@0.3.0
      #   with:
      #        token: ${{ secrets.CLASSIC_TOKEN }}
      #        repo: hivemapper/odc-api
      #        artifact_name: odc-api
      #        wait_seconds: 30
      # - run: |
      #      ls -al odc-api
      #      unzip odc-api
      #      cp dashcam-api.js  dashcam/package/camera-node/files/dashcam-api.js
      #      ls -al dashcam/package/camera-node/files/dashcam-api.js
      #      md5sum dashcam/package/camera-node/files/dashcam-api.js
      - name: configure
        run: |
          make -s -C buildroot/ BR2_EXTERNAL=../dashcam O=../../output raspberrypicm4io_64_dev_dashcam_defconfig
      - name: Compile
        run: |
          cd ../output
          make
      - name: Copy target
        run: |
          mkdir artifacts
          cp ../output/images/update.raucb ./artifacts/firmware_update.raucb
      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Extract firmware version from ODC API
        id: firmware_version
        run: echo "::set-output name=version::$(bash extract_firmware_version.sh)"
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: ${{ steps.timestamp.outputs.date }}-${{ steps.firmware_version.outputs.version }}.raucb
          path: artifacts/firmware_update.raucb
