name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
       token: ${{ secrets.CLASSIC_TOKEN }}
       submodules: recursive
    - name: configure
      run: |
        make -s -C buildroot/ BR2_EXTERNAL=../dashcam O=../../output raspberrypicm4io_64_dev_dashcam_defconfig
    - name: Compile
      run: |
        cd ../output
        make 
    - name: Copy target
      run: |
        pwd
        cp ../output/images/update.raucb ./output/firmware_update.raucb
    - name : Upload 
      uses: actions/upload-artifact@master
      with:
        name: buildroot-hdc
        path: output/images/firmware_update.raucb
    
  
  
