name: compile_hdc

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CLASSIC_TOKEN }}
          submodules: recursive
      - name: configure
        run: |
          make -s -C buildroot/ BR2_EXTERNAL=../dashcam O=../../output raspberrypicm4io_64_dev_dashcam_defconfig
      # Buildroot is not good at picking up when a package needs to be rebuilt.
      # Force clean the most commonly modified packages.
      - name: Compile
        run: |
          cd ../output
          make camera-node-dirclean camera-bridge-dirclean data-logger-dirclean usb-writer-dirclean
          make
      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Extract firmware version from ODC API
        id: firmware_version
        run: echo "::set-output name=version::$(bash extract_firmware_version.sh)"
      - name: Copy target
        run: |
          mkdir artifacts
          cp ../output/images/update.raucb ./artifacts/${{ steps.timestamp.outputs.date }}_${{ steps.firmware_version.outputs.version }}.raucb
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: buildroot-hdc
          path: artifacts/${{ steps.timestamp.outputs.date }}_${{ steps.firmware_version.outputs.version }}.raucb
