name: Deploy

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["compile_hdc"]
    types:
      - completed
    branches:
      - main
jobs:
  deploy:
    name: Upload Firmware to S3
    runs-on: self-hosted
    permissions:
      deployments: write
    steps:
      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          token: ${{ secrets.CLASSIC_TOKEN }}
          artifact_name: buildroot-hdc
          wait_seconds: 30
      - run: |
          ls -al
          unzip -o buildroot-hdc
          ls -al 
          mkdir tmp
          mv -f *.raucb tmp/
      - uses: shallwefootball/s3-upload-action@master
        id: upload_s3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }} 
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: dashcam-firmware
          source_dir: 'tmp/'
          destination_dir: 'cicd'
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "testing 123 ${{steps.upload_s3.outputs.object_locations}}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  
