name: Deploy

on: 
  workflow_dispatch:
jobs:
  deploy:
    name: Upload Firmware to S3
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@master
      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: hivemapper/hdc_firmware
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: buildroot-hdc
          wait_seconds: 60 
      - run: |
          ls -al
          unzip buildroot-hdc.zip
          ls -al 
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'firmware_update.raucb'
          destination_dir: 'firmware_update.raucb'