name: Deploy

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["compile_hdc"]
    types:
      - completed
jobs:
  on-success:
    name: Upload Firmware to S3
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      deployments: write
    steps:
      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          token: ${{ secrets.CLASSIC_TOKEN }}
          artifact_name: buildroot-hdc
          wait_seconds: 30
      - run: |
          ls -al
          unzip buildroot-hdc
          ls -al 
          mkdir tmp
          mv *.raucb tmp/
          echo  ${{ secrets.AWS_KEY_ID }} 
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }} 
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: dashcam-firmware
          source_dir: 'tmp/'
          destination_dir: ${{ github.ref_name}}
  on-failure:
    name: Notify on failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "Could not upload because the build failed."